services:
  - type: web
    name: enginepro-losas-creer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn web_app.backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SMTP_HOST
        value: mail.creeringenieria.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: info@creeringenieria.com
      - key: SMTP_PASS
        sync: false   # <-- lo pones a mano en el dashboard de Render
